#!/usr/bin/env node

// Create new test case. See `./t new` for help.

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { dirname, resolve, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

// Parse flags
const argv = process.argv.slice(2);
let file = '';
let pragma = '';
let input = '';
let desc = '';
const opts = [];

for (let i = 0; i < argv.length; i++) {
  switch (argv[i]) {
    case '--file': file = argv[++i] || ''; break;
    case '--pragma': pragma = argv[++i] || ''; break;
    case '--input': input = argv[++i] || ''; break;
    case '--desc': desc = argv[++i] || ''; break;
    case '--opt': opts.push(argv[++i] || ''); break;
    default:
      console.error('Unknown flag: ' + argv[i]);
      process.exit(1);
  }
}

if (!file || !pragma || !input) {
  console.error('Usage: ./t new --file <path> --pragma <pragma> --input <code> [--desc <desc>] [--opt key=value ...]');
  console.error('');
  console.error('Required:');
  console.error('  --file    Path relative to tests/testcases/ (e.g. using/my_test.md)');
  console.error('  --pragma  PASS | FAIL | "PASS SLOPPY" | "PASS MODULE" | "PASS ANNEXB" | "PASS ANNEXBOTH"');
  console.error('  --input   JS input code');
  console.error('');
  console.error('Optional:');
  console.error('  --desc    Test description');
  console.error('  --opt     key=value parser option (repeatable)');
  process.exit(1);
}

// Validate pragma
const validPragmas = ['PASS', 'FAIL', 'PASS SLOPPY', 'PASS MODULE', 'PASS ANNEXB', 'PASS ANNEXBOTH'];
if (!validPragmas.includes(pragma.toUpperCase())) {
  console.error('Invalid pragma: ' + pragma);
  console.error('Must be one of: ' + validPragmas.join(', '));
  process.exit(1);
}

// Normalize file: ensure .md suffix
if (!file.endsWith('.md')) file += '.md';

// Build full relative path
const relPath = 'tests/testcases/' + file;
const absPath = resolve(projectRoot, relPath);

// Bail if file already exists
if (existsSync(absPath)) {
  console.error('File already exists: ' + relPath);
  process.exit(1);
}

// Derive breadcrumb from path: using/my_file.md => "> :: using\n>\n> ::> my file"
const parts = file.replace('.md', '').split('/');
const dirs = parts.slice(0, -1);
const fileName = parts[parts.length - 1].replace(/_/g, ' ');
const breadcrumb = dirs.length > 0
  ? `> :: ${dirs.join(' : ')}\n>\n> ::> ${fileName}`
  : `> ::> ${fileName}`;

// Build options block
let optionsBlock = '';
if (opts.length > 0) {
  const lines = opts.map(opt => {
    const eq = opt.indexOf('=');
    if (eq < 0) {
      console.error('Invalid option (expected key=value): ' + opt);
      process.exit(1);
    }
    const k = opt.slice(0, eq).trim();
    const v = opt.slice(eq + 1).trim();
    return `- \`${k} = ${v}\``;
  });
  optionsBlock = '\n' + lines.join('\n') + '\n';
}

// Build the .md content (Output section is auto-generated by ./t ff)
const header = desc
  ? `${breadcrumb}\n>\n> ${desc}`
  : breadcrumb;

const content = `# Tenko parser test case

- Path: ${relPath}

${header}

## ${pragma.toUpperCase()}

## Input
${optionsBlock}
\`\`\`\`\`js
${input}
\`\`\`\`\`
`;

// Create parent dirs and write
mkdirSync(dirname(absPath), { recursive: true });
writeFileSync(absPath, content);
console.log('Created: ' + relPath);

// Run ./t ff to generate output
console.log('Running: ./t ff ' + relPath);
try {
  execSync('./t ff ' + relPath, { cwd: projectRoot, stdio: 'inherit' });
} catch (e) {
  console.error('./t ff exited with code ' + e.status);
  process.exit(e.status || 1);
}
